/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros;

import com.mycompany.ferramentas.BancoDeDadosMySql;
import com.mycompany.ferramentas.Formularios;
import com.mycompany.outros.categoria.CadCargo;
import com.mycompany.outros.categoria.CadCidade;
import com.mycompany.outros.categoria.CadEstadoCivil;
import com.mycompany.outros.categoria.CadEventos;
import com.mycompany.outros.categoria.CadPessoa;
import com.mycompany.outros.categoria.ListCargo;
import com.mycompany.outros.categoria.ListCidade;
import com.mycompany.outros.categoria.ListEstadoCivil;
import com.mycompany.outros.categoria.ListEventos;
import com.mycompany.outros.categoria.ListPessoa;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JOptionPane;

/**
 *
 * @author emanuel.4966
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal_Escola
     */
    public Menu_Principal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()) {
            JOptionPane.showMessageDialog(null, "Não foi possível conectar ao banco de dados.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCadastroCidade = new javax.swing.JMenuItem();
        miCadastroPessoa = new javax.swing.JMenuItem();
        miCadastroCargo = new javax.swing.JMenuItem();
        miCadastroEventos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miConsultaCidade = new javax.swing.JMenuItem();
        miConsultaPessoa = new javax.swing.JMenuItem();
        miConsultaCargo = new javax.swing.JMenuItem();
        miConsultaEventos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastros");

        miCadastroCidade.setText("Cidade");
        miCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCidadeActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroCidade);

        miCadastroPessoa.setText("Pessoa");
        miCadastroPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPessoaActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroPessoa);

        miCadastroCargo.setText("Cargo");
        miCadastroCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCargoActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroCargo);

        miCadastroEventos.setText("Eventos");
        miCadastroEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEventosActionPerformed(evt);
            }
        });
        jMenu1.add(miCadastroEventos);

        jMenuItem1.setText("Estado Cívil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        miConsultaCidade.setText("Cidade");
        miConsultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCidadeActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaCidade);

        miConsultaPessoa.setText("Pessoa");
        miConsultaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaPessoa);

        miConsultaCargo.setText("Cargo");
        miConsultaCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCargoActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaCargo);

        miConsultaEventos.setText("Eventos");
        miConsultaEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEventosActionPerformed(evt);
            }
        });
        jMenu2.add(miConsultaEventos);

        jMenuItem2.setText("Estado Cívil");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCidadeActionPerformed
        CadCidade cadCidade = new CadCidade();
        Formularios.cadCidade = cadCidade;
        cadCidade.setVisible(true);  
    }//GEN-LAST:event_miCadastroCidadeActionPerformed

    private void miConsultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCidadeActionPerformed
        ListCidade listCidade = new ListCidade();
        Formularios.listCidade = listCidade;
        listCidade.setVisible(true);
    }//GEN-LAST:event_miConsultaCidadeActionPerformed

    private void miCadastroPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPessoaActionPerformed
        CadPessoa cadPessoa = new CadPessoa();
        Formularios.cadPessoa = cadPessoa;
        cadPessoa.setVisible(true);
    }//GEN-LAST:event_miCadastroPessoaActionPerformed

    private void miConsultaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPessoaActionPerformed
        ListPessoa listPessoa = new ListPessoa();
        Formularios.listPessoa = listPessoa;
        listPessoa.setVisible(true);
    }//GEN-LAST:event_miConsultaPessoaActionPerformed

    private void miCadastroCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCargoActionPerformed
        CadCargo cadCargo = new CadCargo();
        Formularios.cadCargo = cadCargo;
        cadCargo.setVisible(true);
    }//GEN-LAST:event_miCadastroCargoActionPerformed

    private void miConsultaCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCargoActionPerformed
        ListCargo listCargo = new ListCargo();
        Formularios.listCargo = listCargo;
        listCargo.setVisible(true);
    }//GEN-LAST:event_miConsultaCargoActionPerformed

    private void miCadastroEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEventosActionPerformed
        CadEventos cadEventos = new CadEventos();
        Formularios.cadEventos = cadEventos;
        cadEventos.setVisible(true);
    }//GEN-LAST:event_miCadastroEventosActionPerformed

    private void miConsultaEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEventosActionPerformed
        ListEventos listEventos = new ListEventos();
        Formularios.listEventos = listEventos;
        listEventos.setVisible(true);
    }//GEN-LAST:event_miConsultaEventosActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadEstadoCivil cadEstadoCivil = new CadEstadoCivil();
        Formularios.cadEstadoCivil = cadEstadoCivil;
        cadEstadoCivil.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListEstadoCivil listEstadoCivil = new ListEstadoCivil();
        Formularios.listEstadoCivil = listEstadoCivil;
        listEstadoCivil.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem miCadastroCargo;
    private javax.swing.JMenuItem miCadastroCidade;
    private javax.swing.JMenuItem miCadastroEventos;
    private javax.swing.JMenuItem miCadastroPessoa;
    private javax.swing.JMenuItem miConsultaCargo;
    private javax.swing.JMenuItem miConsultaCidade;
    private javax.swing.JMenuItem miConsultaEventos;
    private javax.swing.JMenuItem miConsultaPessoa;
    // End of variables declaration//GEN-END:variables
}
